CXX=g++-8
CXX+=-std=c++17
MAIN=$(shell basename $(CURDIR))
SRC=$(wildcard *.cpp)
OBJ=$(SRC:.cpp=.o)
NAMES=$(SRC:.cpp=)

all: $(MAIN)

$(MAIN):
		echo "dummy"


.PHONY: clean

clean:
	echo "dummy"